---
- name: 'APT : Activation des dépôt Backports'
  copy:
    dest: '/etc/apt/{{ item.path }}'
    backup: yes
    owner: root
    group: root
    mode:  '0644'
    src: '{{ item.filename }}'
  loop:
  - { filename: 'apt_backports_sources',     path: 'sources.list.d/backports.list'}
  - { filename: 'apt_backports_preferences', path: 'preferences.d/backports'}

- name: 'APT : Mise à jour des packages à la dernière version'
  apt:
    update_cache: yes
    upgrade: full

- name: 'Installation des packages communs'
  apt:
    name: '{{ common_packages_list }}'
    state: latest

- name: 'Installation des packages DevOps'
  when: install_pkg_devops|bool
  apt:
    name: '{{ devops_packages_list }}'
    state: latest

- name: 'Installation des packages de développement'
  when: install_pkg_dev|bool
  apt:
    name: '{{ dev_packages_list }}'
    state: latest

- name: 'Installation des packages de développement android'
  when: install_pkg_dev_android|bool
  apt:
    name: '{{ dev_android_packages_list }}'
    state: latest

- name: 'Installation des packages Desktop'
  when: install_pkg_desktop|bool
  apt:
    name: '{{ desktop_packages_list }}'
    state: latest

- name: 'Installation des packages Games'
  when: install_pkg_games|bool
  apt:
    name: '{{ game_packages_list }}'
    state: latest

- name: 'Installation des packages Système'
  when: install_pkg_system|bool
  apt:
    name: '{{ system_packages_list }}'
    state: latest

- name: 'APT : Suppression des paquets inutiles'
  apt:
    autoremove: yes

- name: 'APT : Nettoyage du cache'
  apt:
    autoclean: yes

- name: 'Vim : Configuration /etc/vim/vimrc.local'
  copy:
    dest: /etc/vim/vimrc.local
    backup: yes
    owner: root
    group: root
    mode:  '0644'
    src: vimrc.local

- name: 'profile.d : Copie des fichiers de personnalisation du Shell'
  copy:
    dest: '/etc/profile.d/{{ item | basename }}'
    backup: yes
    owner: root
    group: root
    mode:  '0644'
    src: '{{ item }}'
  with_fileglob:
    - '*.sh'

- name: 'Gitconfig : Configuration /root/.gitconfig'
  copy:
    dest: /root/.gitconfig
    backup: yes
    owner: root
    group: root
    mode:  '0600'
    src: gitconfig
